// Mocks generated by Mockito 5.4.0 from annotations
// in luna/test/bridge_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:luna/Services/SmartHome/bridge_service.dart' as _i2;
import 'package:luna/Services/SmartHome/smart_home_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BridgeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBridgeService extends _i1.Mock implements _i2.BridgeService {
  MockBridgeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkBridge(String? ip) => (super.noSuchMethod(
        Invocation.method(
          #checkBridge,
          [ip],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<List<_i4.Bridge>> getBridges() => (super.noSuchMethod(
        Invocation.method(
          #getBridges,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Bridge>>.value(<_i4.Bridge>[]),
      ) as _i3.Future<List<_i4.Bridge>>);
  @override
  _i3.Future<List<_i4.Bridge>> getBridgesDebug() => (super.noSuchMethod(
        Invocation.method(
          #getBridgesDebug,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Bridge>>.value(<_i4.Bridge>[]),
      ) as _i3.Future<List<_i4.Bridge>>);
  @override
  _i3.Future<String> createUserDebug(String? ip) => (super.noSuchMethod(
        Invocation.method(
          #createUserDebug,
          [ip],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  _i3.Future<dynamic> createUser(String? ip) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [ip],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
