// Mocks generated by Mockito 5.4.0 from annotations
// in luna/test/event_planning_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:device_calendar/device_calendar.dart' as _i2;
import 'package:luna/Services/Calendar/calendar_service.dart' as _i4;
import 'package:luna/Services/Movies/movie_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tmdb_api/tmdb_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceCalendarPlugin_0 extends _i1.SmartFake
    implements _i2.DeviceCalendarPlugin {
  _FakeDeviceCalendarPlugin_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTMDB_1 extends _i1.SmartFake implements _i3.TMDB {
  _FakeTMDB_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarService extends _i1.Mock implements _i4.CalendarService {
  MockCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceCalendarPlugin get calendarPlugin => (super.noSuchMethod(
        Invocation.getter(#calendarPlugin),
        returnValue: _FakeDeviceCalendarPlugin_0(
          this,
          Invocation.getter(#calendarPlugin),
        ),
      ) as _i2.DeviceCalendarPlugin);
  @override
  _i5.Future<String?> getCalendarId() => (super.noSuchMethod(
        Invocation.method(
          #getCalendarId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
  @override
  _i5.Future<_i2.DeviceCalendarPlugin?> requestCalendarPermissions(
          _i2.DeviceCalendarPlugin? calendarPlugin) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestCalendarPermissions,
          [calendarPlugin],
        ),
        returnValue: _i5.Future<_i2.DeviceCalendarPlugin?>.value(),
      ) as _i5.Future<_i2.DeviceCalendarPlugin?>);
  @override
  _i5.Future<List<_i2.Event>> getUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Event>>.value(<_i2.Event>[]),
      ) as _i5.Future<List<_i2.Event>>);
  @override
  _i5.Future<void> createCalendarEvent(
    DateTime? date,
    String? name,
    int? durationInMin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCalendarEvent,
          [
            date,
            name,
            durationInMin,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [MovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieService extends _i1.Mock implements _i6.MovieService {
  MockMovieService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TMDB get tmdb => (super.noSuchMethod(
        Invocation.getter(#tmdb),
        returnValue: _FakeTMDB_1(
          this,
          Invocation.getter(#tmdb),
        ),
      ) as _i3.TMDB);
  @override
  _i5.Future<List<dynamic>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<int> getMovieLength(int? movieId) => (super.noSuchMethod(
        Invocation.method(
          #getMovieLength,
          [movieId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
