// Mocks generated by Mockito 5.4.0 from annotations
// in luna/test/good_night_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:luna/Services/SmartHome/smart_home_model.dart' as _i4;
import 'package:luna/Services/SmartHome/smart_home_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SmartHomeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartHomeService extends _i1.Mock implements _i2.SmartHomeService {
  MockSmartHomeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Light>> getLights(
    dynamic ip,
    dynamic user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLights,
          [
            ip,
            user,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Light>>.value(<_i4.Light>[]),
      ) as _i3.Future<List<_i4.Light>>);
  @override
  List<_i4.Light> responseToLights(Map<String, dynamic>? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #responseToLights,
          [response],
        ),
        returnValue: <_i4.Light>[],
      ) as List<_i4.Light>);
  @override
  _i3.Future<void> turnOffLight(
    _i4.Light? light,
    dynamic ip,
    dynamic user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #turnOffLight,
          [
            light,
            ip,
            user,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
