// Mocks generated by Mockito 5.4.0 from annotations
// in luna/test/movie_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:luna/Services/Movies/movie_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tmdb_api/tmdb_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImages_0 extends _i1.SmartFake implements _i2.Images {
  _FakeImages_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeV3_1 extends _i1.SmartFake implements _i2.V3 {
  _FakeV3_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeV4_2 extends _i1.SmartFake implements _i2.V4 {
  _FakeV4_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTMDB_3 extends _i1.SmartFake implements _i2.TMDB {
  _FakeTMDB_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovies_4 extends _i1.SmartFake implements _i2.Movies {
  _FakeMovies_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTv_5 extends _i1.SmartFake implements _i2.Tv {
  _FakeTv_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeasons_6 extends _i1.SmartFake implements _i2.TvSeasons {
  _FakeTvSeasons_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvEpisodes_7 extends _i1.SmartFake implements _i2.TvEpisodes {
  _FakeTvEpisodes_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeople_8 extends _i1.SmartFake implements _i2.People {
  _FakePeople_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCredit_9 extends _i1.SmartFake implements _i2.Credit {
  _FakeCredit_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCertification_10 extends _i1.SmartFake implements _i2.Certification {
  _FakeCertification_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChanges_11 extends _i1.SmartFake implements _i2.Changes {
  _FakeChanges_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollections_12 extends _i1.SmartFake implements _i2.Collections {
  _FakeCollections_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFind_13 extends _i1.SmartFake implements _i2.Find {
  _FakeFind_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeners_14 extends _i1.SmartFake implements _i2.Geners {
  _FakeGeners_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenres_15 extends _i1.SmartFake implements _i2.Genres {
  _FakeGenres_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeywords_16 extends _i1.SmartFake implements _i2.Keywords {
  _FakeKeywords_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompanies_17 extends _i1.SmartFake implements _i2.Companies {
  _FakeCompanies_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrending_18 extends _i1.SmartFake implements _i2.Trending {
  _FakeTrending_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearch_19 extends _i1.SmartFake implements _i2.Search {
  _FakeSearch_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiscover_20 extends _i1.SmartFake implements _i2.Discover {
  _FakeDiscover_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworks_21 extends _i1.SmartFake implements _i2.Networks {
  _FakeNetworks_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReviews_22 extends _i1.SmartFake implements _i2.Reviews {
  _FakeReviews_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuth_23 extends _i1.SmartFake implements _i2.Auth {
  _FakeAuth_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLists_24 extends _i1.SmartFake implements _i2.Lists {
  _FakeLists_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccount_25 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGuestSession_26 extends _i1.SmartFake implements _i2.GuestSession {
  _FakeGuestSession_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TMDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTMDB extends _i1.Mock implements _i2.TMDB {
  MockTMDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get defaultLanguage => (super.noSuchMethod(
        Invocation.getter(#defaultLanguage),
        returnValue: '',
      ) as String);
  @override
  _i2.Images get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: _FakeImages_0(
          this,
          Invocation.getter(#images),
        ),
      ) as _i2.Images);
  @override
  _i2.V3 get v3 => (super.noSuchMethod(
        Invocation.getter(#v3),
        returnValue: _FakeV3_1(
          this,
          Invocation.getter(#v3),
        ),
      ) as _i2.V3);
  @override
  _i2.V4 get v4 => (super.noSuchMethod(
        Invocation.getter(#v4),
        returnValue: _FakeV4_2(
          this,
          Invocation.getter(#v4),
        ),
      ) as _i2.V4);
  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieService extends _i1.Mock implements _i3.MovieService {
  MockMovieService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TMDB get tmdb => (super.noSuchMethod(
        Invocation.getter(#tmdb),
        returnValue: _FakeTMDB_3(
          this,
          Invocation.getter(#tmdb),
        ),
      ) as _i2.TMDB);
  @override
  _i4.Future<List<dynamic>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);
  @override
  _i4.Future<int> getMovieLength(int? movieId) => (super.noSuchMethod(
        Invocation.method(
          #getMovieLength,
          [movieId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [V3].
///
/// See the documentation for Mockito's code generation for more information.
class MockV3 extends _i1.Mock implements _i2.V3 {
  MockV3() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Movies get movies => (super.noSuchMethod(
        Invocation.getter(#movies),
        returnValue: _FakeMovies_4(
          this,
          Invocation.getter(#movies),
        ),
      ) as _i2.Movies);
  @override
  _i2.Tv get tv => (super.noSuchMethod(
        Invocation.getter(#tv),
        returnValue: _FakeTv_5(
          this,
          Invocation.getter(#tv),
        ),
      ) as _i2.Tv);
  @override
  _i2.TvSeasons get tvSeasons => (super.noSuchMethod(
        Invocation.getter(#tvSeasons),
        returnValue: _FakeTvSeasons_6(
          this,
          Invocation.getter(#tvSeasons),
        ),
      ) as _i2.TvSeasons);
  @override
  _i2.TvEpisodes get tvEpisodes => (super.noSuchMethod(
        Invocation.getter(#tvEpisodes),
        returnValue: _FakeTvEpisodes_7(
          this,
          Invocation.getter(#tvEpisodes),
        ),
      ) as _i2.TvEpisodes);
  @override
  _i2.People get people => (super.noSuchMethod(
        Invocation.getter(#people),
        returnValue: _FakePeople_8(
          this,
          Invocation.getter(#people),
        ),
      ) as _i2.People);
  @override
  _i2.Credit get credit => (super.noSuchMethod(
        Invocation.getter(#credit),
        returnValue: _FakeCredit_9(
          this,
          Invocation.getter(#credit),
        ),
      ) as _i2.Credit);
  @override
  _i2.Certification get certification => (super.noSuchMethod(
        Invocation.getter(#certification),
        returnValue: _FakeCertification_10(
          this,
          Invocation.getter(#certification),
        ),
      ) as _i2.Certification);
  @override
  _i2.Changes get changes => (super.noSuchMethod(
        Invocation.getter(#changes),
        returnValue: _FakeChanges_11(
          this,
          Invocation.getter(#changes),
        ),
      ) as _i2.Changes);
  @override
  _i2.Collections get collections => (super.noSuchMethod(
        Invocation.getter(#collections),
        returnValue: _FakeCollections_12(
          this,
          Invocation.getter(#collections),
        ),
      ) as _i2.Collections);
  @override
  _i2.Find get find => (super.noSuchMethod(
        Invocation.getter(#find),
        returnValue: _FakeFind_13(
          this,
          Invocation.getter(#find),
        ),
      ) as _i2.Find);
  @override
  _i2.Geners get geners => (super.noSuchMethod(
        Invocation.getter(#geners),
        returnValue: _FakeGeners_14(
          this,
          Invocation.getter(#geners),
        ),
      ) as _i2.Geners);
  @override
  _i2.Genres get genres => (super.noSuchMethod(
        Invocation.getter(#genres),
        returnValue: _FakeGenres_15(
          this,
          Invocation.getter(#genres),
        ),
      ) as _i2.Genres);
  @override
  _i2.Keywords get keywords => (super.noSuchMethod(
        Invocation.getter(#keywords),
        returnValue: _FakeKeywords_16(
          this,
          Invocation.getter(#keywords),
        ),
      ) as _i2.Keywords);
  @override
  _i2.Companies get companies => (super.noSuchMethod(
        Invocation.getter(#companies),
        returnValue: _FakeCompanies_17(
          this,
          Invocation.getter(#companies),
        ),
      ) as _i2.Companies);
  @override
  _i2.Trending get trending => (super.noSuchMethod(
        Invocation.getter(#trending),
        returnValue: _FakeTrending_18(
          this,
          Invocation.getter(#trending),
        ),
      ) as _i2.Trending);
  @override
  _i2.Search get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _FakeSearch_19(
          this,
          Invocation.getter(#search),
        ),
      ) as _i2.Search);
  @override
  _i2.Discover get discover => (super.noSuchMethod(
        Invocation.getter(#discover),
        returnValue: _FakeDiscover_20(
          this,
          Invocation.getter(#discover),
        ),
      ) as _i2.Discover);
  @override
  _i2.Networks get networks => (super.noSuchMethod(
        Invocation.getter(#networks),
        returnValue: _FakeNetworks_21(
          this,
          Invocation.getter(#networks),
        ),
      ) as _i2.Networks);
  @override
  _i2.Reviews get reviews => (super.noSuchMethod(
        Invocation.getter(#reviews),
        returnValue: _FakeReviews_22(
          this,
          Invocation.getter(#reviews),
        ),
      ) as _i2.Reviews);
  @override
  _i2.Auth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuth_23(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.Auth);
  @override
  _i2.Lists get lists => (super.noSuchMethod(
        Invocation.getter(#lists),
        returnValue: _FakeLists_24(
          this,
          Invocation.getter(#lists),
        ),
      ) as _i2.Lists);
  @override
  _i2.Account get account => (super.noSuchMethod(
        Invocation.getter(#account),
        returnValue: _FakeAccount_25(
          this,
          Invocation.getter(#account),
        ),
      ) as _i2.Account);
  @override
  _i2.GuestSession get guestSession => (super.noSuchMethod(
        Invocation.getter(#guestSession),
        returnValue: _FakeGuestSession_26(
          this,
          Invocation.getter(#guestSession),
        ),
      ) as _i2.GuestSession);
}

/// A class which mocks [Movies].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovies extends _i1.Mock implements _i2.Movies {
  MockMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<dynamic, dynamic>> getDetails(
    int? movieId, {
    String? language,
    String? appendToResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetails,
          [movieId],
          {
            #language: language,
            #appendToResponse: appendToResponse,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getAlternativeTitle(
    int? movieId, {
    String? country = r'US',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlternativeTitle,
          [movieId],
          {#country: country},
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getCredits(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCredits,
          [movieId],
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getExternalIds(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExternalIds,
          [movieId],
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getKeywords(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeywords,
          [movieId],
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getReleaseDates(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReleaseDates,
          [movieId],
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getVideos(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideos,
          [movieId],
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getTranslations(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslations,
          [movieId],
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getRecommended(
    int? movieId, {
    String? language,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommended,
          [movieId],
          {
            #language: language,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getSimilar(
    int? movieId, {
    String? language,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSimilar,
          [movieId],
          {
            #language: language,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getReviews(
    int? movieId, {
    String? language,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviews,
          [movieId],
          {
            #language: language,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getLists(
    int? movieId, {
    String? language,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [movieId],
          {
            #language: language,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getLatest({String? language}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatest,
          [],
          {#language: language},
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getNowPlaying({
    String? language,
    int? page = 1,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlaying,
          [],
          {
            #language: language,
            #page: page,
            #region: region,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getPouplar({
    String? language,
    int? page = 1,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPouplar,
          [],
          {
            #language: language,
            #page: page,
            #region: region,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getPopular({
    String? language,
    int? page = 1,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopular,
          [],
          {
            #language: language,
            #page: page,
            #region: region,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getTopRated({
    String? language,
    int? page = 1,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRated,
          [],
          {
            #language: language,
            #page: page,
            #region: region,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getUpcoming({
    String? language,
    int? page = 1,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcoming,
          [],
          {
            #language: language,
            #page: page,
            #region: region,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<dynamic> getWatchProviders(int? movieId) => (super.noSuchMethod(
        Invocation.method(
          #getWatchProviders,
          [movieId],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
  @override
  _i4.Future<Map<dynamic, dynamic>> rateMovie(
    int? movieId,
    double? ratingValue, {
    String? guestSessionId,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateMovie,
          [
            movieId,
            ratingValue,
          ],
          {
            #guestSessionId: guestSessionId,
            #sessionId: sessionId,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> deleteRating(
    int? movieId, {
    String? guestSessionId,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRating,
          [movieId],
          {
            #guestSessionId: guestSessionId,
            #sessionId: sessionId,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getImages(
    int? movieId, {
    String? language,
    String? includeImageLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImages,
          [movieId],
          {
            #language: language,
            #includeImageLanguage: includeImageLanguage,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getAccountStatus(
    int? movieId, {
    String? sessionId,
    String? guestSessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountStatus,
          [movieId],
          {
            #sessionId: sessionId,
            #guestSessionId: guestSessionId,
          },
        ),
        returnValue:
            _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i4.Future<Map<dynamic, dynamic>>);
}
