// Mocks generated by Mockito 5.4.0 from annotations
// in luna/test/philips_hue_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:luna/Services/SmartHome/bridge_model.dart' as _i3;
import 'package:luna/Services/SmartHome/bridge_preferences.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBridgePreferences_0 extends _i1.SmartFake
    implements _i2.BridgePreferences {
  _FakeBridgePreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BridgeModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockBridgeModel extends _i1.Mock implements _i3.BridgeModel {
  MockBridgeModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BridgePreferences get userPreferences => (super.noSuchMethod(
        Invocation.getter(#userPreferences),
        returnValue: _FakeBridgePreferences_0(
          this,
          Invocation.getter(#userPreferences),
        ),
      ) as _i2.BridgePreferences);
  @override
  set userPreferences(_i2.BridgePreferences? _userPreferences) =>
      super.noSuchMethod(
        Invocation.setter(
          #userPreferences,
          _userPreferences,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: '',
      ) as String);
  @override
  String get ip => (super.noSuchMethod(
        Invocation.getter(#ip),
        returnValue: '',
      ) as String);
  @override
  set setUser(String? value) => super.noSuchMethod(
        Invocation.setter(
          #setUser,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set setIpAddress(String? value) => super.noSuchMethod(
        Invocation.setter(
          #setIpAddress,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i4.Future<void> deleteBridgePreferences() => (super.noSuchMethod(
        Invocation.method(
          #deleteBridgePreferences,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> getBridgePreferences() => (super.noSuchMethod(
        Invocation.method(
          #getBridgePreferences,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
